<div class="row">
<div class="col-sm">
<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company-footer-block')->toHtml();
?>
</div>
<div class="col-sm">
<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-contact-us-block')->toHtml();
?>
</div>
<div class="col-sm">
<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-payment-block')->toHtml();
?>
</div>
</div>
<script type="text/javascript">
(function  () {
    require(["jquery"], function($) {
        $(document).ready(function($) {
        console.log('footer-links working ok');

        });
    });
})();
</script>
